# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 11:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fackultet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_department', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=80)),
                ('facult_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Fackultet')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curse_count', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('schedule', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=15), size=9)),
                ('group_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Group')),
            ],
        ),
    ]
