# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('schedule_file', models.FileField(upload_to='')),
                ('group_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Group')),
            ],
        ),
        migrations.DeleteModel(
            name='Shedule',
        ),
    ]
