# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_department', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_file',
        ),
    ]
