# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20160916_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='curse_count',
        ),
    ]
